### register a user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "first_name": null,
    "last_name": null,
    "email": null,
    "password": null,
    "role_id": null
}

### login a user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": null,
    "password": null
}