### list all categories
GET http://localhost:3000/api/categories
Authorization: Bearer {{}}

### get a category
GET http://localhost:3000/api/categories/1
Authorization: Bearer {{}}

### create a category
POST http://localhost:3000/api/categories
Content-Type: application/json
Authorization: Bearer {{}}

{
  "name": null,
  "state_id": null
}

### update a category
PUT http://localhost:3000/api/categories/1
Content-Type: application/json
Authorization: Bearer {{}}

{
  "name": null
}

### change category status
PUT http://localhost:3000/api/categories/1/state
Authorization: Bearer {{}}

{
  "state_id": null
}