### create an order
POST http://localhost:3000/api/orders
Content-Type: application/json
Authorization: Bearer {{}}

{
    "address": null,
    "phone_number": null,
    "total_amount": null,
    "state_id": null,
    "order_details": [
        {"quantity": null, "price": null, "product_id": null}
    ]
}

### update an order
PUT http://localhost:3000/api/orders/1
Content-Type: application/json
Authorization: Bearer {{}}

{
    "address": null,
    "phone_number": null
}

### change order status
PUT http://localhost:3000/api/orders/1/state
Content-Type: application/json
Authorization: Bearer {{}}

{
    "state_id": null
}